export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  LEARN: '/learn',
  QUIZ: '/quiz',
  STATS: '/stats',
  LIBRARY: '/library',
  SCHOOL_PLANS: '/school-plans',
  BUSINESS: '/business',
  PRIVACY: '/privacy',
  TOEIC: '/toeic',
  IELTS_ACADEMIC: '/ielts-academic',
  IELTS_GENERAL: '/ielts-general',
  LEARN_ROOM: (roomId: string) => `/learn/${roomId}`,
  QUIZ_ROOM: (roomId: string) => `/quiz/${roomId}`,
  TOEIC_TEST: (id: string) => `/toeic/${id}`,
  TOEIC_PART: (id: string, part: string) => `/toeic/${id}/${part}`,
} as const;
